### ISSUE TITLE
Must rename Employees Controller to something else

### ISSUE THREAD

**Issue by alexandralaudon** [alexandralaudon/ActiveHelperOne#3]
The Employees Controller, views folder, and route are all named inappropriately because this process is supposed to account for all possible schemas, not just the employees schema I initially created. 

Choices Kate & I have come up with so far:
1-MainsController
2-GenericsController
3-RootsController
4-PrincipalController
5-Questions/Answers Controller

Please submit reasons for choosing one or the other.

**Comment by alexandralaudon** [comment]
I'm down with calling this the QueriesController. If an additional controller is needed, the QueriesController won't change. 

i.e. OutputsController. Thoughts?

**Comment by katekilian** [comment]
Yes, QueriesController is fine, because ultimately that IS what the UI will be doing with the tables is constructing a query.  Completely agreed. 

Change approved, go for making another branch with the change and I'll approve ASAP :+1:

**Comment by alexandralaudon** [comment]
Made changes in the renameToGenericMVC pull request.
